// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-LG6Z5XnErviGMnoIe7SayK-8ik5ej0',
    appId: '1:430702711255:web:d8d5b37d481f8e811bbb92',
    messagingSenderId: '430702711255',
    projectId: 'spotify-clone-4d0ba',
    authDomain: 'spotify-clone-4d0ba.firebaseapp.com',
    storageBucket: 'spotify-clone-4d0ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv29GwCzFypAHRFfD6Zx3h6TpZMwtxpqA',
    appId: '1:430702711255:android:abb53dcd5c4b47561bbb92',
    messagingSenderId: '430702711255',
    projectId: 'spotify-clone-4d0ba',
    storageBucket: 'spotify-clone-4d0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshACjrxq0HdKbwz9vuga6u-ZsWjfmIS4',
    appId: '1:430702711255:ios:7ee4f3263f7e0bb81bbb92',
    messagingSenderId: '430702711255',
    projectId: 'spotify-clone-4d0ba',
    storageBucket: 'spotify-clone-4d0ba.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBshACjrxq0HdKbwz9vuga6u-ZsWjfmIS4',
    appId: '1:430702711255:ios:7ee4f3263f7e0bb81bbb92',
    messagingSenderId: '430702711255',
    projectId: 'spotify-clone-4d0ba',
    storageBucket: 'spotify-clone-4d0ba.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2-LG6Z5XnErviGMnoIe7SayK-8ik5ej0',
    appId: '1:430702711255:web:e57cb9170da541a31bbb92',
    messagingSenderId: '430702711255',
    projectId: 'spotify-clone-4d0ba',
    authDomain: 'spotify-clone-4d0ba.firebaseapp.com',
    storageBucket: 'spotify-clone-4d0ba.appspot.com',
  );
}
